version: '3.7'

services:

  client:
    container_name: react-client
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - './client:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
  
  server:
    container_name: graphql-server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 5001:5000